Feature: Retweet a Tweet
  This feature file describes the behaviour of the system for POST requests at the endpoint on /api/tweets/{tweetId}/retweets to retweet a specified tweet.
  There should be follwoing behaviour at the system:
  - If the request contains the header "Authorization" with a valid token of an user, then a new retweet of the specified tweet will be created for the requesting user http response state will be 201
  - If the specified tweet is already a retweet, then the new created tweet has the same root-tweet as the specified tweet
  - If the request doesn´t contain a valid token, then there will be no new retweet created and the http response state will be 401
  - If the request contains a valid token which belongs to a moderator, then there will be no new retweet created and the http response state will be 403
  - If the specified tweet doesn´t exist or is in state "CANCELED", then there will be no new retweet created and its state will be 404



  Scenario: Retweet a tweet
  Request to like a specified tweet

    Given the user "max" is authenticated
    And a stored tweet with id 1
    When a client sends a "POST" "/tweets/1/retweets" request for user "max" to retweet the tweet with id 1
    Then the HTTP response status-code will be 201
    And the HTTP response body contains following JSON of a new retweet from tweet with id 1, while the tweetId and the publish-date got generated by the system
        """
          {
              "tweetId": 12,
              "content": "Example content",
              "pubDate": 1552498895703,
              "author": {
                  "userId": 0,
                  "firstName": "Max",
                  "lastName": "Mustermann",
                  "role": "USER"
              },
              "rootTweet": {
                  "tweetId": 1,
                  "content": "Example content",
                  "pubDate": 1549015871000,
                  "author": {
                      "userId": 0,
                      "firstName": "Max",
                      "lastName": "Mustermann",
                      "role": "USER"
                  },
                  "rootTweet": null
              }
          }
        """

  Scenario: Tweet to retweet is already a retweet
  The specified tweet is already a retweet
  The root-tweet of the new created retweet will be the same as the one from the specified tweet

    Given the user "max" is authenticated
    And a stored retweet with id 2 from tweet with id 1
    When a client sends a "POST" "/tweets/2/retweets" request for user "max" to retweet the tweet with id 2
    Then the HTTP response status-code will be 201



  Scenario: Unauthorised request to retweet a tweet
  The request must contain a valid token of a user

    When a client sends a request without a valid token to retweet a specified tweet
    Then the HTTP response status-code will be 401



  Scenario: Token from request to retweet a tweet belongs to a moderator
  Account must be from an user

    Given the moderator "werner" is authenticated
    When a client sends a request for moderator "werner" to retweet a specified tweet
    Then the HTTP response status-code will be 403



  Scenario: Specified tweet to retweet doesn´t exist
  The user must exist

    Given there is no tweet with id 9999
    When a client sends a request to retweet the tweet with id 9999
    Then the HTTP response status-code will be 404


  Scenario: Specified tweet to retweet is in status CANCELED
  The tweet must not be in status CANCELED

    Given a stored tweet with id 1 in status CANCELED from user "max"
    When a client sends a request to retweet the tweet with id 1
    Then the HTTP response status-code will be 404