Feature: Retweet a Tweet
  This feature file describes the behaviour of the system for POST requests at the endpoint on /api/tweets/{tweetId}/retweets to retweet a specified tweet.
  There should be follwoing behaviour at the system:
  - If the request contains the header "Authorization" with a valid token of an user, then a new retweet of the specified tweet will be created for the requesting user http response state will be 201
  - If the specified tweet is already a retweet, then the new created tweet has the same root-tweet as the specified tweet
  - If the request doesn´t contain a valid token, then there will be no new retweet created and the http response state will be 401
  - If the request contains a valid token which belongs to a moderator, then there will be no new retweet created and the http response state will be 403
  - If the specified tweet doesn´t exist or is in state "CANCELED", then there will be no new retweet created and its state will be 404



  Scenario: Retweet a tweet
  Request to like a specified tweet

    Given the user "max" is authenticated
    And a stored tweet with id 1
    When a client sends a "POST" "/tweets/1/retweets" request for user "max" to retweet the tweet with id 1
    Then the HTTP response status-code will be <status code>
    And the HTTP response body contains following JSON of a new retweet from tweet with id 1, while the tweetId and the publish-date got generated by the system
        """
            {
                "tweetId": 5,
                "content": "An example content",
                "author" : {
                    "userId": 0,
                    "firstName": "Max",
                    "lastName": "Mustermann",
                    "role": "USER"
                },
                "rootTweet": null
            }
        """