package de.openknowledge.playground.api.rest.security.stepDefinition;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import cucumber.api.PendingException;
import cucumber.api.java.en.Then;
import de.openknowledge.playground.api.rest.security.domain.tweet.DetailedTweet;
import de.openknowledge.playground.api.rest.security.domain.tweet.TweetDTO;
import de.openknowledge.playground.api.rest.security.supportCode.SharedDomain;
import de.openknowledge.playground.api.rest.security.supportCode.converter.convertedClasses.ErrorMessage;
import de.openknowledge.playground.api.rest.security.domain.accounts.UserDTO;
import io.restassured.response.Response;
import org.hamcrest.Matchers;

import javax.ws.rs.core.MediaType;
import java.io.IOException;
import java.util.List;

public class ResponseSteps {
    private SharedDomain domain;

    public ResponseSteps (SharedDomain domain) {
        this.domain = domain;
    }


    @Then("the HTTP response body contains following JSON of an error message:")
    public void the_HTTP_response_body_contains_following_JSON_of_an_error_message(ErrorMessage expectedErrorMessage) {
        domain.getResponse().then()
                .contentType(MediaType.APPLICATION_JSON)
                .body("errorMessage", Matchers.equalTo(expectedErrorMessage.getErrorMessage()));
    }

    @Then("the HTTP response status-code will be {int}")
    public void the_HTTP_response_status_code_will_be(Integer expectedStatusCode) {
        Response response = domain.getResponse();
        response.then()
                .statusCode(expectedStatusCode);
    }

    @Then("the HTTP response body contains following JSON of a new Tweet, while the tweetId and the publish-date got generated by the system")
    public void the_HTTP_response_body_contains_following_JSON_of_a_new_Tweet_while_the_tweetId_and_the_publish_date_got_generated_by_the_system(TweetDTO expectedTweet) {
        domain.getResponse().then()
                .contentType(MediaType.APPLICATION_JSON)
                .body("content", Matchers.equalTo(expectedTweet.getContent()))
                .body("author.firstName", Matchers.equalTo(expectedTweet.getAuthor().getFirstName()))
                .body("author.lastName", Matchers.equalTo(expectedTweet.getAuthor().getLastName()))
                .body("author.role", Matchers.equalTo(expectedTweet.getAuthor().getRole().toString()))
                .body("rootTweet", Matchers.isEmptyOrNullString());
    }


    @Then("the HTTP response body contains following JSON of the follower from user john")
    public void the_HTTP_response_body_contains_following_JSON_of_the_follower_from_user_john(String expectedJson) {
        try {
            List<UserDTO> users = new ObjectMapper().readValue(expectedJson, new TypeReference<List<UserDTO>>() {});
            domain.getResponse().then()
                    .body("size()", Matchers.equalTo(users.size()));

            for (int i=0; i<users.size(); i++) {
            domain.getResponse().then()
                    .contentType(MediaType.APPLICATION_JSON)
                    .body("["+i+"].userId", Matchers.equalTo(users.get(i).getUserId()))
                    .body("["+i+"].firstName", Matchers.equalTo(users.get(i).getFirstName()))
                    .body("["+i+"].lastName", Matchers.equalTo(users.get(i).getLastName()))
                    .body("["+i+"].role", Matchers.equalTo(users.get(i).getRole().toString()));
            }

        } catch (IOException e) {
            throw new PendingException();
        }
    }

    @Then("the HTTP response body will contain following JSON with a list of users who liked the stored tweet:")
    public void the_HTTP_response_body_will_contain_following_JSON_with_a_list_of_users_who_liked_the_stored_tweet(String expectedJson) {
        try {
            List<UserDTO> users = new ObjectMapper().readValue(expectedJson, new TypeReference<List<UserDTO>>() {});
            domain.getResponse().then()
                    .body("size()", Matchers.equalTo(users.size()));

            for (int i=0; i<users.size(); i++) {
                domain.getResponse().then()
                        .contentType(MediaType.APPLICATION_JSON)
                        .body("["+i+"].userId", Matchers.equalTo(users.get(i).getUserId()))
                        .body("["+i+"].firstName", Matchers.equalTo(users.get(i).getFirstName()))
                        .body("["+i+"].lastName", Matchers.equalTo(users.get(i).getLastName()))
                        .body("["+i+"].role", Matchers.equalTo(users.get(i).getRole().toString()));
            }

        } catch (IOException e) {
            throw new PendingException();
        }
    }


    @Then("the HTTP response body will contain following JSON with detailed information about the tweet with id 1")
    public void the_HTTP_response_body_will_contain_following_JSON_with_detailed_information_about_the_tweet_with_id(String expectedJson) {
        DetailedTweet expectedTweet = null;
        try {
            expectedTweet = new ObjectMapper().readValue(expectedJson, DetailedTweet.class);
        } catch (IOException e) {
            throw new PendingException();
        }

        domain.getResponse().then()
                .contentType(MediaType.APPLICATION_JSON)
                .body("tweetId", Matchers.equalTo(expectedTweet.getTweetId()))
                .body("content", Matchers.equalTo(expectedTweet.getContent()))
                .body("author.userId", Matchers.equalTo(expectedTweet.getAuthor().getUserId()))
                .body("author.firstName", Matchers.equalTo(expectedTweet.getAuthor().getFirstName()))
                .body("author.lastName", Matchers.equalTo(expectedTweet.getAuthor().getLastName()))
                .body("numLiker", Matchers.equalTo(expectedTweet.getNumLiker()))
                .body("numRetweets", Matchers.equalTo(expectedTweet.getNumRetweets()));
    }


    @Then("the HTTP response body will contain following JSON with tweets from users max is following")
    public void the_HTTP_response_body_will_contain_following_JSON_with_tweets_from_users_max_is_following(String expectedJson) {
        List<TweetDTO> expectedTweets = null;
        try {
            expectedTweets = new ObjectMapper().readValue(expectedJson, new TypeReference<List<TweetDTO>>(){});
        } catch (IOException e) {
            e.printStackTrace();
        }
        domain.getResponse().then()
                .contentType(MediaType.APPLICATION_JSON)
                .body("size()", Matchers.equalTo(expectedTweets.size()));

        for (int i=0; i<expectedTweets.size(); i++) {
            domain.getResponse().then()
                    .body("["+i+"].tweetId", Matchers.equalTo(expectedTweets.get(i).getTweetId()))
                    .body("["+i+"].content", Matchers.equalTo(expectedTweets.get(i).getContent()))
                    .body("["+i+"].author.userId", Matchers.equalTo(expectedTweets.get(i).getAuthor().getUserId()))
                    .body("["+i+"].author.firstName", Matchers.equalTo(expectedTweets.get(i).getAuthor().getFirstName()))
                    .body("["+i+"].author.lastName", Matchers.equalTo(expectedTweets.get(i).getAuthor().getLastName()))
                    .body("["+i+"].rootTweet", Matchers.equalTo(expectedTweets.get(i).getRootTweet()));
        }
    }
}
