INSERT INTO TAB_USER(USR_ID, USR_USERNAME) VALUES (1, '@admin');
INSERT INTO TAB_USER(USR_ID, USR_USERNAME) VALUES (2, '@stephan');
INSERT INTO TAB_USER(USR_ID, USR_USERNAME) VALUES (3, '@sven');
INSERT INTO TAB_USER(USR_ID, USR_USERNAME) VALUES (4, '@realDonaldTrump');
INSERT INTO TAB_USER(USR_ID, USR_USERNAME) VALUES (5, '@trumpFan');

INSERT INTO TAB_FOLLOWER(FLR_USR_ID, FLR_FLR_ID) VALUES (1, 2);
INSERT INTO TAB_FOLLOWER(FLR_USR_ID, FLR_FLR_ID) VALUES (1, 3);
INSERT INTO TAB_FOLLOWER(FLR_USR_ID, FLR_FLR_ID) VALUES (1, 4);
INSERT INTO TAB_FOLLOWER(FLR_USR_ID, FLR_FLR_ID) VALUES (2, 3);
INSERT INTO TAB_FOLLOWER(FLR_USR_ID, FLR_FLR_ID) VALUES (3, 2);
INSERT INTO TAB_FOLLOWER(FLR_USR_ID, FLR_FLR_ID) VALUES (4, 2);
INSERT INTO TAB_FOLLOWER(FLR_USR_ID, FLR_FLR_ID) VALUES (4, 3);
INSERT INTO TAB_FOLLOWER(FLR_USR_ID, FLR_FLR_ID) VALUES (4, 5);

INSERT INTO TAB_TWEET(TWT_ID, TWT_TWEET, TWT_USR_ID, TWT_CREATED_AT, TWT_MODIFIED_AT) VALUES (1, 'Windmills are the greatest threat in the US to both bald and golden eagles. Media claims fictional global warming is worse', 4, '2017-01-01 16:23:00', '2017-01-01 16:23:00');
INSERT INTO TAB_TWEET(TWT_ID, TWT_TWEET, TWT_USR_ID, TWT_CREATED_AT, TWT_MODIFIED_AT) VALUES (2, 'Sorry losers and haters, but my I.Q. is one of the highest - and you all know it! Please dont feel so stupid or insecure, its not your fault', 4, '2017-01-04 10:14:00', '2017-01-04 10:14:00');
INSERT INTO TAB_TWEET(TWT_ID, TWT_TWEET, TWT_USR_ID, TWT_CREATED_AT, TWT_MODIFIED_AT) VALUES (3, 'We should have gotten more of the oil in Syria, and we should have gotten more of the oil in Iraq. Dumb leaders', 4, '2017-01-20 20:45:00', '2017-01-20 20:45:00');

INSERT INTO TAB_LIKE(LIK_TWT_ID, LIK_USR_ID) VALUES (1, 5);
INSERT INTO TAB_LIKE(LIK_TWT_ID, LIK_USR_ID) VALUES (2, 5);
INSERT INTO TAB_LIKE(LIK_TWT_ID, LIK_USR_ID) VALUES (3, 5);
