INSERT INTO TAB_ACCOUNT(ACCOUNT_TYPE, ACCOUNT_ID, USERNAME, FIRST_NAME, LAST_NAME, ROLE) VALUES ('USER', 0, 'max', 'Max', 'Mustermann', 0);
INSERT INTO TAB_ACCOUNT(ACCOUNT_TYPE, ACCOUNT_ID, USERNAME, FIRST_NAME, LAST_NAME, ROLE) VALUES ('USER', 1, 'marta', 'Marta', 'Musterfrau', 0);
INSERT INTO TAB_ACCOUNT(ACCOUNT_TYPE, ACCOUNT_ID, USERNAME, FIRST_NAME, LAST_NAME, ROLE) VALUES ('USER', 2, 'john', 'John', 'Doe', 0);
INSERT INTO TAB_ACCOUNT(ACCOUNT_TYPE, ACCOUNT_ID, USERNAME, FIRST_NAME, LAST_NAME, ROLE) VALUES ('USER', 3, 'jane', 'Jane', 'Doe', 0);
INSERT INTO TAB_ACCOUNT(ACCOUNT_TYPE, ACCOUNT_ID, USERNAME, FIRST_NAME, LAST_NAME, ROLE) VALUES ('MODERATOR', 4, 'werner', 'Werner', 'Pflanzen', 1);
INSERT INTO TAB_ACCOUNT(ACCOUNT_TYPE, ACCOUNT_ID, USERNAME, FIRST_NAME, LAST_NAME, ROLE) VALUES ('USER', 5, 'karl', 'Karl', 'Ranseier', 0);
INSERT INTO TAB_ACCOUNT(ACCOUNT_TYPE, ACCOUNT_ID, USERNAME, FIRST_NAME, LAST_NAME, ROLE) VALUES ('USER', 6, 'lena', 'Lena', 'Löchte', 0);